### ISSUE TITLE
authentication issues with pipx and wrong requests version [solution]

### ISSUE THREAD

**Issue by mbafford** [ndbeals/keep-exporter#1]
Just leaving this here for anyone encountering the same issue. From:
https://github.com/kiwiz/gkeepapi/issues/81#issuecomment-762884244

If you install using [pipx](https://pipxproject.github.io/pipx/) you might have issues with authentication failing. This isn't an issue with the username/password, but an issue with one of the Python libraries. If you use `2.23.0` of `requests`, it works perfectly:

```
pipx install keep-exporter 
pipx inject keep-exporter requests===2.23.0
```

I was then able to set up keep-exporter and sync my notes, using a [Google app password](https://myaccount.google.com/apppasswords).

----

Thank you for publishing this project.

**Comment by ndbeals** [comment]
Glad it was of some use for you!

Thanks for the information, I'm going to leave this issue open until I update the README.

**Comment by ndbeals** [comment]
Updated the readme with this, thanks.
