### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by chaoscreater** [ndbeals/keep-exporter#15]
I've tried to follow the instructions as best as I can, but can't figure out how to get this working.

First of all, the instructions mentions this file "keep_export", but it's not found in any of the folders.

I've got poetry installed and ran poetry build to build the wheel and everything during the install process went OK. I can't just figure out how to run. I tried running the export.py file and initially I got a click-config-file module missing error. I fixed that by doing **pip3 install click-config-file** and then I tried again and I got no more errors, but nothing happens when I ran the export.py file.

I've got nothing like what is mentioned in the help file.

**Comment by mbafford** [comment]
If you're not really comfortable with Python or familiar with the ecosystem, pipx might be a better way of installing - it sets up a self-contained virtual environment, downloads the package, installs dependencies, and sets up your path for you.

```
$ pip3 install pipx
$ pipx ensurepath 

then:

$ pipx install keep-exporter
$ pipx inject keep-exporter requests===2.23.0  # not sure if this step is still needed
$ keep_export
```

---

I don't use poetry often, so I'm not 100% for the poetry steps, but I did just test:

```$ git clone https://github.com/ndbeals/keep-exporter
$ cd keep-exporter
$  poetry install
Creating virtualenv keep-exporter-a9pX0pV0-py3.9 in /Users/mbafford/Library/Caches/pypoetry/virtualenvs
$ poetry build
```

This creates the files in `dist/` that the README references, so then you can do:

```
pip3 install dist/keep_exporter-*.whl
```

(it seems like you successfully did all of that)

This installs all of the relevant dependencies and adds the keep_export script to the same path as `pip3`, so you should just be able to run `keep_export` with no path:

```
$ keep_export
User:
```

It should be in the same folder as `pip3`.

`keep_export` is only generated as part of the build/install process. Again, if the build and install went fine, it should be right beside pip3 in your filesystem.

**Comment by chaoscreater** [comment]
Thanks. I ran keep_export just now and it is prompting for my username etc. I initially thought that keep_export is a python file and couldn't find it in the folder, but it makes sense now.

I would like to run this as a scheduled task. To do that, I would need to store my Google keep configurations as a file and use it in a script or something. I see that there is a config.example file. Do I just remove the .example extension to use it?

Also, I found keep_export.exe in the same folder as pip3. I just did a test run and it exported all my notes, that's good. Problem is, I don't know where it exported the notes to. I looked at the folder where keep_export.exe is located, but I don't see my Google Keep notes there. I checked the project folder that I cloned from Github and it's not there either.

**Comment by mbafford** [comment]
You can use the config file, but it's not mentioned in the help.

```
keep_export --config /path/to/keep-exporter-config.yaml
```

or another way of running using `poetry` without installing the wheel/.whl file:

```
poetry run keep_exporter/export.py --config /path/to/keep-exporter-config.yaml
```

As for the location of the files - my config has, e.g.:

```
directory = "/path/to/export/gkeep-export/"
rename_local = True
delete_local = True
```

It seems like you're running on Windows? I'm not sure if there are differences that are causing issues - unfortunately I'm not really able to help troubleshoot too much on Windows.

**Comment by ndbeals** [comment]
Cheers @mbafford, Really appreciate you answering this (just saw this issue too).

**Comment by mbafford** [comment]
@ndbeals No problem! 

@chaoscreater I'm going to close this now, but I'm happy to try to help further if you're still having issues. Just let us know if you're having any remaining issues and any supporting details so we can help troubleshoot.
