### ISSUE TITLE
Convert "label" json metadata to "tag" YAML metadata

### ISSUE THREAD

**Issue by agichim** [ndbeals/keep-exporter#16]
Google Keep has a feature called Labels, basically it acts like tags or categories. It would be amazing if they could be converted as tags in the YAML frontmatter. When exporting Google Keep with Takeout it gives a .json file with the metadata and Labels looks as below.

```
...
    "labels": [
        {
            "name": "tag1"
        },
        {
            "name": "tag2"
        }
    ]
...
```
Convert from the metadata above to YAML:
```
tags: tag1, tag2
```

**Comment by mbafford** [comment]
This was added by https://github.com/ndbeals/keep-exporter/commit/a3007464033fc68b1c42db00485b5abd7777e4bc for #12, but it looks like the version in PyPI wasn't updated with some of the more recent changes.

Until the PyPI is updated, you can install this with `pipx` directly from the git repository and get this feature:
```pipx install git+https://github.com/ndbeals/keep-exporter```.

The tag format will be in YAML format, so:

```
tags:
- tag1
- tag2
```

**Comment by ndbeals** [comment]
@agichim The Pypi release has been updated.
