### ISSUE TITLE
pypi version is out of date (bump version and update pypi)

### ISSUE THREAD

**Issue by mbafford** [ndbeals/keep-exporter#19]
Last push to PyPI was 21-Jan, which is missing a number of enhancements from 26-Jan.

Need to bump the version and upload to PyPI.

**Comment by ndbeals** [comment]
Thanks @mbafford, you're the best.

**Comment by mbafford** [comment]
@ndbeals I don't think this is done - still showing - v1.2.0 2021-01-21:
https://pypi.org/project/keep-exporter/#history

I'm not sure what's involved to push the project to pypi.

**Comment by ndbeals** [comment]
Ahh yes i forgot to bump the version history.
