### ISSUE TITLE
Remove meta info from top of notes exported

### ISSUE THREAD

**Issue by f0rkth1s** [ndbeals/keep-exporter#2]
Is it possible to remove the extra meta data from the top of exported notes?

color: White
deleted: false
id: xxxxxxxxxxxxxxxxxx
parent_id: root
pinned: false
sort: '0'
timestamps:
created: 1414924214.261
edited: 1414929007.851
trashed: -3600.0
updated: 1526783775.947
title: xxxx
trashed: false
type: List
url: https://keep.google.com/u/0/#LIST/xxxxxxxxxxxxxxxxxxxxxxxxx

Other than this, it worked perfectly! Many thanks

**Comment by ndbeals** [comment]
I can make excluding metadata an optional flag, I'll put that on my TODO

**Comment by f0rkth1s** [comment]
Awesome, thanks so much. My wife and I are currently in the process of de-googling and this is the last hurdle.
Moving all my notes to Joplin instead., hosted on Joplin

**Comment by ndbeals** [comment]
I have added a `--header/--no-header` flag that includes/excludes the frontmatter. In your case, add `--no-header` to the command, it defaults to including it.
