### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 450: character maps to <undefined>

### ISSUE THREAD

**Issue by chaoscreater** [ndbeals/keep-exporter#27]
Seems like this doesn't work with Python 3.9. 

![image](https://user-images.githubusercontent.com/18227319/228268941-872a6b89-2de6-45fe-9998-b8f0b7652093.png)

**Comment by chaoscreater** [comment]
Never mind, I got it working. Had to remove all the virtualenv created by poetry and re-do everything from scratch. Tested working with Python 3.9. Seems like it's broken on 3.7.

**Comment by ndbeals** [comment]
Thanks for the heads up, It seems like I'll need to update the dependencies
