### ISSUE TITLE
Format checkboxes in markdown syntax

### ISSUE THREAD

**Issue by mbafford** [ndbeals/keep-exporter#3]
Currently the checkboxes come across as unicode check/uncheck squares, would be nice to have them formatted in Markdown format:

- [ ] uncheck
- [X] checked

I tested this rough version locally:

Before `frontmatter.Post`:
```python
text = note.text
text = text.replace('☑ ', '- [X] ')
text = text.replace('☐ ', '- [ ] ')
return frontmatter.Post(text, handler=None, **metadata)
```

**Comment by ndbeals** [comment]
Functionality added in pull request #5. Closed
