### ISSUE TITLE
Include annotations - attached links

### ISSUE THREAD

**Issue by mbafford** [ndbeals/keep-exporter#4]
When you add a link to a keep note, Google adds the link as an annotation. These persist even if the link text is removed from the note.

These can be added with something like this:

```python
    if note.annotations.links:
        text = text + "\n## Links \n\n"

        for a in note.annotations.links:
            text += "- [%s](%s)\n" % ( a.title, a.url )
```

Probably better to use a Markdown formatter to ensure the link title/URL won't cause problems.

**Comment by mbafford** [comment]
Annotation [are not documented](https://gkeepapi.readthedocs.io/en/latest/#annotations), I just found them by poking at the notes object in a debugger. They were actually the primary item of interest for a couple of notes which lead me to your tool.

**Comment by ndbeals** [comment]
Functionality added in pull request #5. Closed
